/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Semester4;

/**
 *
 * @author Soni Hendarkanto PTI 4B
 * 
 */

import java.awt.event.*;
import javax.swing.*;

public class Tugas1Kamus extends javax.swing.JFrame {

    /**
     * Creates new form Tugas1Kamus
     */
    public Tugas1Kamus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TUGAS 1");

        jPanel1.setBackground(new java.awt.Color(204, 0, 255));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KAMUS SANGAT SEDERHANA SEKALI");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Translate Nama Hewan Bahasa Indonesia ke Bahasa Inggris");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTextField1.setToolTipText("Tekan tombol PROSES atau ENTER disini untuk memproses translate");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel1.setText("Masukkan kata yg ingin di translate :");

        jButton1.setText("PROSES");
        jButton1.setToolTipText("Eksekusi juragan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Translate Result :");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField2.setToolTipText("Hasil translate akan muncul di sini");

        jButton2.setText("CLEAR ALL");
        jButton2.setToolTipText("Bersihkan semua");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Soni Hendarkanto PTI 4B");

        jButton3.setText("Daftar Kata");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Tombol Proses untuk eksekusi:
        if(jTextField1.getText().equalsIgnoreCase("Burung"))
        {
            jTextField2.setText("Bird of Prey");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Cicak"))
        {
            jTextField2.setText("House lizard on The Wall");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Buaya"))
        {
            jTextField2.setText("Crocodile of Arabasta Kingdom");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Naga"))
        {
            jTextField2.setText("Dragon Natsu Dragneel");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Ular"))
        {
            jTextField2.setText("Snake on The Plane");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Cacing"))
        {
            jTextField2.setText("Worm virus");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Nyamuk"))
        {
            jTextField2.setText("Mosquito bite");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Anjing"))
        {
            jTextField2.setText("Dog tooth");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Gajah"))
        {
            jTextField2.setText("Elephant Zootopia");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Singa"))
        {
            jTextField2.setText("Lion king of the street");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Ikan"))
        {
            jTextField2.setText("Fish in the Hole");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Rusa"))
        {
            jTextField2.setText("oh my Deer...");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Beruang"))
        {
            jTextField2.setText("Bear... (but not Bir)");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Paus"))
        {
            jTextField2.setText("Whale is very Rare");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Harimau"))
        {
            jTextField2.setText("Tiger from Java");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Kuda"))
        {
            jTextField2.setText("Horse of the dead");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Unta"))
        {
            jTextField2.setText("Chamel white 20's Bold Filter");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("tokek"))
        {
            jTextField2.setText("Gecko Moria of Shichibukai");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Kenari"))
        {
            jTextField2.setText("Mockingjay The Hunger Games");
                    }
        else if(jTextField1.getText().equalsIgnoreCase("Betet"))
        {
            jTextField2.setText("Parrot like Jack Sparrow");
                    }
        else if(jTextField1.getText().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Masukkan Kata !!!!");
            jTextField2.setText("Cilukbaaaa... Ketik dulu kata yang ingin di artiakann ?!?!?!");
                    }
        else jTextField2.setText("salah kataaaaaaaaaaa juragan.......");
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Tombol CLEAR ALL mengosongkan Text Field:
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // syntax agar Text field bisa di eksekusi dengan ENTER:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(jTextField1.getText().equalsIgnoreCase("Burung"))
            {
                jTextField2.setText("Bird of Prey");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Cicak"))
            {
                jTextField2.setText("House lizard on The Wall");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Buaya"))
            {
                jTextField2.setText("Crocodile of Arabasta Kingdom");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Naga"))
            {
                jTextField2.setText("Dragon Natsu Dragneel");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Ular"))
            {
                jTextField2.setText("Snake on The Plane");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Cacing"))
            {
                jTextField2.setText("Worm virus");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Nyamuk"))
            {
                jTextField2.setText("Mosquito bite");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Anjing"))
            {
                jTextField2.setText("Dog tooth");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Gajah"))
            {
                jTextField2.setText("Elephant Zootopia");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Singa"))
            {
                jTextField2.setText("Lion king of the street");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Ikan"))
            {
                jTextField2.setText("Fish in the Hole");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Rusa"))
            {
                jTextField2.setText("oh my Deer...");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Beruang"))
            {
                jTextField2.setText("Bear... (but not Bir)");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Paus"))
            {
                jTextField2.setText("Whale is very Rare");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Harimau"))
            {
                jTextField2.setText("Tiger from Java");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Kuda"))
            {
                jTextField2.setText("Horse of the dead");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Unta"))
            {
                jTextField2.setText("Chamel white 20's Bold Filter");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("tokek"))
            {
                jTextField2.setText("Gecko Moria of Shichibukai");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Kenari"))
            {
                jTextField2.setText("Mockingjay The Hunger Games");
                    }
            else if(jTextField1.getText().equalsIgnoreCase("Betet"))
            {
                jTextField2.setText("Parrot like Jack Sparrow");
                    }
            else if(jTextField1.getText().equalsIgnoreCase(""))
            {
                // Memunculkan kotak dialog:
                JOptionPane.showMessageDialog(rootPane, "Masukkan Kata !!!!");
                jTextField2.setText("Cilukbaaaa... Ketik dulu kata yang ingin di artiakann ?!?!?!");
                    }
            else jTextField2.setText("salah kataaaaaaaaaaa juragan.......");
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Tombol Daftar Kata memunculkan kotak dialog:
        JOptionPane.showMessageDialog(rootPane, "Burung, Cicak, Buaya, Naga, Ular, Cacing \n"
                + "Nyamuk, Anjing, Gajah, Singa, Ikan, Rusa \n"
                + "Beruang, Paus, Harimau, Kuda, Unta, Tokek \n"
                + "Kenari, Betet", "Daftar Kata Nama Hewan", HEIGHT);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas1Kamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas1Kamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas1Kamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas1Kamus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1Kamus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
