package Semester4;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Soni Hendarkanto PTI 4B
 */
public class Tugas2Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Tugas2Kalkulator
     */
    public Tugas2Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NoxLabelAngka1 = new javax.swing.JLabel();
        NoxTextAngka1 = new javax.swing.JTextField();
        NoxLabelAngka2 = new javax.swing.JLabel();
        NoxTextAngka2 = new javax.swing.JTextField();
        noxButtonTambah = new javax.swing.JButton();
        NoxLabelHasil = new javax.swing.JLabel();
        NoxTextHasil = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        noxButtonKurang = new javax.swing.JButton();
        noxButtonKali = new javax.swing.JButton();
        noxButtonBagi = new javax.swing.JButton();
        noxButtonCLEAR = new javax.swing.JButton();
        close = new javax.swing.JButton();
        about = new javax.swing.JButton();
        noxButtonSamaDengan = new javax.swing.JButton();
        NoxTextHasil2 = new javax.swing.JTextField();
        NoxLabelHasil1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tugas 2 Kalkulator");
        setBackground(new java.awt.Color(0, 153, 153));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kalkulator Sederhana yang penting jalan");
        jLabel1.setToolTipText("Untuk menghitung hutang....");

        jSeparator1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N

        NoxLabelAngka1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        NoxLabelAngka1.setText("Angka 1 :");

        NoxTextAngka1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        NoxTextAngka1.setText("0");
        NoxTextAngka1.setToolTipText("Maskukkan angka pertama yg ingin di hitung");
        NoxTextAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxTextAngka1ActionPerformed(evt);
            }
        });
        NoxTextAngka1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NoxTextAngka1KeyTyped(evt);
            }
        });

        NoxLabelAngka2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        NoxLabelAngka2.setText("Angka 2 :");

        NoxTextAngka2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        NoxTextAngka2.setText("0");
        NoxTextAngka2.setToolTipText("Maskukkan angka Kedua yg ingin di hitung");
        NoxTextAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxTextAngka2ActionPerformed(evt);
            }
        });
        NoxTextAngka2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NoxTextAngka2KeyTyped(evt);
            }
        });

        noxButtonTambah.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        noxButtonTambah.setText("+");
        noxButtonTambah.setToolTipText("Penjumlahan");
        noxButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noxButtonTambahActionPerformed(evt);
            }
        });

        NoxLabelHasil.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        NoxLabelHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoxLabelHasil.setText("Hasil Tombol Sama Dengan :");

        NoxTextHasil.setEditable(false);
        NoxTextHasil.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        NoxTextHasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoxTextHasil.setText("0");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        noxButtonKurang.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        noxButtonKurang.setText("-");
        noxButtonKurang.setToolTipText("Pengurangan");
        noxButtonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noxButtonKurangActionPerformed(evt);
            }
        });

        noxButtonKali.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        noxButtonKali.setText("x");
        noxButtonKali.setToolTipText("Perkalian");
        noxButtonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noxButtonKaliActionPerformed(evt);
            }
        });

        noxButtonBagi.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        noxButtonBagi.setText("/");
        noxButtonBagi.setToolTipText("Pembagian");
        noxButtonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noxButtonBagiActionPerformed(evt);
            }
        });

        noxButtonCLEAR.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        noxButtonCLEAR.setText("CLEAR ALL");
        noxButtonCLEAR.setToolTipText("Kosongkan Semua brooo");
        noxButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noxButtonCLEARActionPerformed(evt);
            }
        });

        close.setFont(new java.awt.Font("Liberation Sans", 3, 12)); // NOI18N
        close.setText("CLOSE");
        close.setToolTipText("Exit");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        about.setFont(new java.awt.Font("Liberation Sans", 3, 12)); // NOI18N
        about.setText("ABOUT");
        about.setToolTipText("Tentang program ini");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        noxButtonSamaDengan.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        noxButtonSamaDengan.setText("=");
        noxButtonSamaDengan.setToolTipText("Pilih dulu tanda hitung diatas...");
        noxButtonSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noxButtonSamaDenganActionPerformed(evt);
            }
        });

        NoxTextHasil2.setEditable(false);
        NoxTextHasil2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        NoxTextHasil2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoxTextHasil2.setText("0");
        NoxTextHasil2.setToolTipText("Klik dulu tombol =");

        NoxLabelHasil1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        NoxLabelHasil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoxLabelHasil1.setText("Hasil Langsung :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(close)
                        .addGap(257, 257, 257)
                        .addComponent(noxButtonCLEAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(about)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NoxLabelAngka2)
                                        .addGap(18, 18, 18)
                                        .addComponent(NoxTextAngka2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NoxLabelAngka1)
                                        .addGap(18, 18, 18)
                                        .addComponent(NoxTextAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(noxButtonSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(noxButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noxButtonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noxButtonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noxButtonBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NoxTextHasil2)
                                .addComponent(NoxTextHasil)
                                .addComponent(NoxLabelHasil1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                            .addComponent(NoxLabelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 102, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoxLabelAngka1)
                            .addComponent(NoxTextAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoxLabelAngka2)
                            .addComponent(NoxTextAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noxButtonTambah)
                            .addComponent(noxButtonKurang)
                            .addComponent(noxButtonKali)
                            .addComponent(noxButtonBagi))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NoxLabelHasil1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoxTextHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NoxLabelHasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoxTextHasil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noxButtonSamaDengan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close)
                    .addComponent(about)
                    .addComponent(noxButtonCLEAR))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // variabel global :
    double NoxAngka1, NoxAngka2, NoxHasil;
    int tanda;

    // Fungsi filter untuk validasi hanya boleh input angka
    private void FilterAngka(KeyEvent s) {
        if (Character.isAlphabetic(s.getKeyChar())) {
            s.consume();
            JOptionPane.showMessageDialog(null, "Maat, Anda salah input... \n"
                    + "Hanya menerima input Angka !!!");
        }
    }

    private void NoxTextAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxTextAngka1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoxTextAngka1ActionPerformed

    private void NoxTextAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxTextAngka2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoxTextAngka2ActionPerformed

    private void noxButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noxButtonTambahActionPerformed
        // code untuk tombol tambah +
        tanda = 1;
        NoxAngka1 = Double.parseDouble(NoxTextAngka1.getText());
        NoxAngka2 = Double.parseDouble(NoxTextAngka2.getText());
        NoxHasil = NoxAngka1 + NoxAngka2;
        NoxTextHasil.setText(Double.toString(NoxHasil));
    }//GEN-LAST:event_noxButtonTambahActionPerformed

    private void NoxTextAngka1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoxTextAngka1KeyTyped
        // Memasukkan fungsi Filter validasi angka pada event -> Key Typed
        FilterAngka(evt);
    }//GEN-LAST:event_NoxTextAngka1KeyTyped

    private void NoxTextAngka2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoxTextAngka2KeyTyped
        // Memasukkan fungsi Filter validasi angka pada event -> Key Typed
        FilterAngka(evt);
    }//GEN-LAST:event_NoxTextAngka2KeyTyped

    private void noxButtonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noxButtonKurangActionPerformed
        // code untuk tombol Kurang -
        tanda = 2;
        NoxAngka1 = Double.parseDouble(NoxTextAngka1.getText());
        NoxAngka2 = Double.parseDouble(NoxTextAngka2.getText());
        NoxHasil = NoxAngka1 - NoxAngka2;
        NoxTextHasil.setText(Double.toString(NoxHasil));
    }//GEN-LAST:event_noxButtonKurangActionPerformed

    private void noxButtonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noxButtonKaliActionPerformed
        // code untuk tombol Kali X
        tanda = 3;
        NoxAngka1 = Double.parseDouble(NoxTextAngka1.getText());
        NoxAngka2 = Double.parseDouble(NoxTextAngka2.getText());
        NoxHasil = NoxAngka1 * NoxAngka2;
        NoxTextHasil.setText(Double.toString(NoxHasil));
    }//GEN-LAST:event_noxButtonKaliActionPerformed

    private void noxButtonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noxButtonBagiActionPerformed
        // code untuk tombol Bagi /
        tanda = 4;
        NoxAngka1 = Double.parseDouble(NoxTextAngka1.getText());
        NoxAngka2 = Double.parseDouble(NoxTextAngka2.getText());
        NoxHasil = NoxAngka1 / NoxAngka2;
        NoxTextHasil.setText(Double.toString(NoxHasil));
    }//GEN-LAST:event_noxButtonBagiActionPerformed

    private void noxButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noxButtonCLEARActionPerformed
        // code untuk tombol CLEAR kosongkan semua
        NoxTextAngka1.setText("");
        NoxTextAngka2.setText("");
        NoxTextHasil.setText("");
        NoxTextHasil2.setText("");
    }//GEN-LAST:event_noxButtonCLEARActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // code tomblo CLOSE keluar exit
        System.exit(WIDTH);
    }//GEN-LAST:event_closeActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // code tombol about tentang
        JOptionPane.showMessageDialog(rootPane, "Di buat oleh: \n\n"
                + "Soni Hendarkanto\n"
                + "PTI 4B");
    }//GEN-LAST:event_aboutActionPerformed

    private void noxButtonSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noxButtonSamaDenganActionPerformed
        // code untuk tombol Sama Dengan =
        switch (tanda) {
            case 1:
                NoxAngka1 = Double.parseDouble(NoxTextAngka1.getText());
                NoxAngka2 = Double.parseDouble(NoxTextAngka2.getText());
                NoxHasil = NoxAngka1 + NoxAngka2;
                //NoxTextHasil.setText(Double.toString(NoxHasil));
                break;
            case 2:
                NoxAngka1 = Double.parseDouble(NoxTextAngka1.getText());
                NoxAngka2 = Double.parseDouble(NoxTextAngka2.getText());
                NoxHasil = NoxAngka1 - NoxAngka2;
                //NoxTextHasil.setText(Double.toString(NoxHasil));
                break;
            case 3:
                NoxAngka1 = Double.parseDouble(NoxTextAngka1.getText());
                NoxAngka2 = Double.parseDouble(NoxTextAngka2.getText());
                NoxHasil = NoxAngka1 * NoxAngka2;
                //NoxTextHasil.setText(Double.toString(NoxHasil));
                break;
            case 4:
                NoxAngka1 = Double.parseDouble(NoxTextAngka1.getText());
                NoxAngka2 = Double.parseDouble(NoxTextAngka2.getText());
                NoxHasil = NoxAngka1 / NoxAngka2;
                //NoxTextHasil.setText(Double.toString(NoxHasil));
                break;
        }
        NoxTextHasil2.setText(Double.toString(NoxHasil));
    }//GEN-LAST:event_noxButtonSamaDenganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas2Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas2Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas2Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas2Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas2Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoxLabelAngka1;
    private javax.swing.JLabel NoxLabelAngka2;
    private javax.swing.JLabel NoxLabelHasil;
    private javax.swing.JLabel NoxLabelHasil1;
    private javax.swing.JTextField NoxTextAngka1;
    private javax.swing.JTextField NoxTextAngka2;
    private javax.swing.JTextField NoxTextHasil;
    private javax.swing.JTextField NoxTextHasil2;
    private javax.swing.JButton about;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton noxButtonBagi;
    private javax.swing.JButton noxButtonCLEAR;
    private javax.swing.JButton noxButtonKali;
    private javax.swing.JButton noxButtonKurang;
    private javax.swing.JButton noxButtonSamaDengan;
    private javax.swing.JButton noxButtonTambah;
    // End of variables declaration//GEN-END:variables
}
