package Semester4;

//import sonihendarkuliah.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author montox
 */
public class Tugas3_SoalPilihanGanda extends javax.swing.JFrame {
    
    //daftar soal dan jawaban dalam bentuk Array
    String[]NoxTanya={"SOAL 1: Nama Buah Iblis Monkey D.Luffy","SOAL 2: Vice Admiral Smooker tipe buah iblis nya ?","SOAL 3: Julukan dari Admiral Sengkoku adalah ?","SOAL 4: Nama pedang terbaru Roronoa Zorro adalah ?"};
    String[]NoxA={"Hito-Hito No Mi model NIKA","Paramecia","Kakek peyot","Pedang Pora"};
    String[]NoxB={"Buah Anggur","LOGIA","Komandan","Pedang Laser"};
    String[]NoxC={"Buah Apel","Zoan","The Budha","Nogososro Sabuk Inten"};
    String[]NoxD={"Buah Bibir","Hybrida pestisida","Jendral","ENMA"};
    String[]NoxJWB={"a","b","c","d"};
    int index = 0;

    /**
     * Creates new form Tugas3_SoalPilihanGanda
     */
    public Tugas3_SoalPilihanGanda() {
        initComponents();
        
        this.setResizable(false); // agar windows tidak bisa di perbesar (Maximize / Non Sizeable)

        // Agar posisi windows di tengah layar, mengambil ukuran layar, butuh import java.awt.*;
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // Agar posisi windows di tengah layar, membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        
        muncul(0);
        NoxButtonPrev_.setVisible(false); //agar tombol Prev hilang dari layar awal
    }
    
    public void muncul(int i){
        NoxFieldPertanyaan_.setText(NoxTanya[i]);
        NoxButtonA_.setText("A.  "+NoxA[i]);
        NoxButtonB_.setText("B.  "+NoxB[i]);
        NoxButtonC_.setText("C.  "+NoxC[i]);
        NoxButtonD_.setText("D.  "+NoxD[i]);
    }
    
    public void Cek_NoxJWB(String m){
        if (m.equals(NoxJWB[index])) {
            JOptionPane.showMessageDialog(rootPane, "BENAR");
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Jawaban kamu SALAH !!!", "SALAH", HEIGHT);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        NoxFieldPertanyaan_ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NoxButtonA_ = new javax.swing.JButton();
        NoxButtonB_ = new javax.swing.JButton();
        NoxButtonC_ = new javax.swing.JButton();
        NoxButtonD_ = new javax.swing.JButton();
        NoxButtonPrev_ = new javax.swing.JButton();
        NoxButtonNext_ = new javax.swing.JButton();
        NoxAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soni H -- Tugas 3 Soal Pilihan Ganda (JAVA PTI 4B)");

        jLabel1.setBackground(new java.awt.Color(51, 255, 153));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Soal Pilihan Ganda PTI 4B");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jLabel2.setText("Pertanyaan:");

        NoxFieldPertanyaan_.setEditable(false);
        NoxFieldPertanyaan_.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        NoxFieldPertanyaan_.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoxFieldPertanyaan_.setText("TextPertanyaan");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        jLabel3.setText("Pilih Jawaban:");

        NoxButtonA_.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        NoxButtonA_.setText("A");
        NoxButtonA_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NoxButtonA_MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NoxButtonA_MouseReleased(evt);
            }
        });
        NoxButtonA_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxButtonA_ActionPerformed(evt);
            }
        });

        NoxButtonB_.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        NoxButtonB_.setText("B");
        NoxButtonB_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NoxButtonB_MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NoxButtonB_MouseReleased(evt);
            }
        });
        NoxButtonB_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxButtonB_ActionPerformed(evt);
            }
        });

        NoxButtonC_.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        NoxButtonC_.setText("C");
        NoxButtonC_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NoxButtonC_MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NoxButtonC_MouseReleased(evt);
            }
        });
        NoxButtonC_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxButtonC_ActionPerformed(evt);
            }
        });

        NoxButtonD_.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        NoxButtonD_.setText("D");
        NoxButtonD_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NoxButtonD_MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NoxButtonD_MouseReleased(evt);
            }
        });
        NoxButtonD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxButtonD_ActionPerformed(evt);
            }
        });

        NoxButtonPrev_.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        NoxButtonPrev_.setText("Prev");
        NoxButtonPrev_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NoxButtonPrev_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NoxButtonPrev_MouseExited(evt);
            }
        });
        NoxButtonPrev_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxButtonPrev_ActionPerformed(evt);
            }
        });

        NoxButtonNext_.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        NoxButtonNext_.setText("Next");
        NoxButtonNext_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NoxButtonNext_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NoxButtonNext_MouseExited(evt);
            }
        });
        NoxButtonNext_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxButtonNext_ActionPerformed(evt);
            }
        });

        NoxAbout.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        NoxAbout.setText("?");
        NoxAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoxAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator1))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NoxFieldPertanyaan_)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoxButtonA_, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoxButtonB_, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoxButtonPrev_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoxButtonC_, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoxButtonD_, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoxButtonNext_, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NoxAbout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoxFieldPertanyaan_, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoxButtonA_, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NoxButtonB_, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NoxButtonC_, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NoxButtonD_, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoxButtonPrev_)
                    .addComponent(NoxButtonNext_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(NoxAbout))
        );

        setSize(new java.awt.Dimension(801, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NoxButtonA_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonA_MousePressed
        // Tombol berubah warna ketika di klik
        NoxButtonA_.setBackground(Color.red);
    }//GEN-LAST:event_NoxButtonA_MousePressed

    private void NoxButtonA_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonA_MouseReleased
        // Tombol berubah warna ketika klik di lepas
        NoxButtonA_.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_NoxButtonA_MouseReleased

    private void NoxButtonB_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonB_MouseReleased
        // Tombol berubah warna ketika klik di lepas
        NoxButtonB_.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_NoxButtonB_MouseReleased

    private void NoxButtonC_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonC_MouseReleased
        // Tombol berubah warna ketika klik di lepas
        NoxButtonC_.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_NoxButtonC_MouseReleased

    private void NoxButtonD_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonD_MouseReleased
        // Tombol berubah warna ketika klik di lepas
        NoxButtonD_.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_NoxButtonD_MouseReleased

    private void NoxButtonD_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonD_MousePressed
        // Tombol berubah warna ketika di klik
        NoxButtonD_.setBackground(Color.red);
    }//GEN-LAST:event_NoxButtonD_MousePressed

    private void NoxButtonB_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonB_MousePressed
        // Tombol berubah warna ketika di klik
        NoxButtonB_.setBackground(Color.red);
    }//GEN-LAST:event_NoxButtonB_MousePressed

    private void NoxButtonC_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonC_MousePressed
        // Tombol berubah warna ketika di klik
        NoxButtonC_.setBackground(Color.red);
    }//GEN-LAST:event_NoxButtonC_MousePressed

    private void NoxButtonNext_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonNext_MouseEntered
        // Tombol berubah warna ketika Cursor berada diatas tombol (Mouse Over)
        NoxButtonNext_.setBackground(Color.BLUE);
    }//GEN-LAST:event_NoxButtonNext_MouseEntered

    private void NoxButtonNext_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonNext_MouseExited
        // Tombol berubah warna ketika Cursor keluar dari area tombol (Mouse Out)
        NoxButtonNext_.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_NoxButtonNext_MouseExited

    private void NoxButtonPrev_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonPrev_MouseEntered
        // Tombol berubah warna ketika Cursor berada diatas tombol (Mouse Over)
        NoxButtonPrev_.setBackground(Color.BLUE);
    }//GEN-LAST:event_NoxButtonPrev_MouseEntered

    private void NoxButtonPrev_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoxButtonPrev_MouseExited
        // Tombol berubah warna ketika Cursor keluar dari area tombol (Mouse Out)
        NoxButtonPrev_.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_NoxButtonPrev_MouseExited

    private void NoxButtonA_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxButtonA_ActionPerformed
        // TODO add your handling code here:
        Cek_NoxJWB("a");
    }//GEN-LAST:event_NoxButtonA_ActionPerformed

    private void NoxButtonB_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxButtonB_ActionPerformed
        // TODO add your handling code here:
        Cek_NoxJWB("b");
    }//GEN-LAST:event_NoxButtonB_ActionPerformed

    private void NoxButtonC_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxButtonC_ActionPerformed
        // TODO add your handling code here:
        Cek_NoxJWB("c");
    }//GEN-LAST:event_NoxButtonC_ActionPerformed

    private void NoxButtonD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxButtonD_ActionPerformed
        // TODO add your handling code here:
        Cek_NoxJWB("d");
    }//GEN-LAST:event_NoxButtonD_ActionPerformed

    private void NoxButtonNext_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxButtonNext_ActionPerformed
        // TODO add your handling code here:
        index++;
        muncul(index);
        
        if (index == 1) {
            NoxButtonPrev_.setVisible(true);
        }
        if (index == 3) {
            NoxButtonNext_.setVisible(false);
        }
        else {
            NoxButtonNext_.setVisible(true);
        }
    }//GEN-LAST:event_NoxButtonNext_ActionPerformed

    private void NoxButtonPrev_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxButtonPrev_ActionPerformed
        // TODO add your handling code here:
        index--;
        muncul(index);
        
        if (index == 0) {
            NoxButtonPrev_.setVisible(false);
        }
        else {
            NoxButtonPrev_.setVisible(true);
            NoxButtonNext_.setVisible(true);
        }
    }//GEN-LAST:event_NoxButtonPrev_ActionPerformed

    private void NoxAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoxAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Matkul Pemgorgraman JAVA Lanjut \n"
                + "PTI 4B \n"
                + "Soni Hendarkanto \n\n"
                + "Tugas 3 Membuat Program Soal Pilihan Ganda Sederhana \n"
                + "Sabtu 4 Maret 2023 \n\n"
                + "Hanya bisa copas dan (sangat) sedikit modif dari coding yg ditunjukkan oleh pak dosen Rozi \n"
                + "Belum bisa membuat variasi yg lebih complex \n\n"
                + "---One Piece Fans---", "Tentang Program ini", HEIGHT);
    }//GEN-LAST:event_NoxAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas3_SoalPilihanGanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas3_SoalPilihanGanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas3_SoalPilihanGanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas3_SoalPilihanGanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas3_SoalPilihanGanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NoxAbout;
    private javax.swing.JButton NoxButtonA_;
    private javax.swing.JButton NoxButtonB_;
    private javax.swing.JButton NoxButtonC_;
    private javax.swing.JButton NoxButtonD_;
    private javax.swing.JButton NoxButtonNext_;
    private javax.swing.JButton NoxButtonPrev_;
    private javax.swing.JTextField NoxFieldPertanyaan_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
