/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sem4_Kriptografi;

import java.awt.*;
import java.io.*;
import java.net.*;

/**
 *
 * @author montox
 */
public class Readme extends javax.swing.JFrame {

    /**
     * Creates new form Readme
     */
    public Readme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TextWikipedia_ = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        TextWikipedia2_ = new javax.swing.JLabel();
        TextSSLIndonesia_ = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextSoniHendar_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Readme");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 3, 13)); // NOI18N
        jLabel2.setText("Apa itu MD5 ?");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Dalam kriptografi, MD5 (Message-Digest algorithm 5) adalah fungsi hash kriptografik yang digunakan secara luas dengan hash value 128-bit. \nPada standart Internet (RFC 1321), MD5 telah dimanfaatkan secara bermacam-macam pada aplikasi keamanan, dan MD5 juga umum digunakan untuk melakukan pengujian integritas sebuah berkas.\n\nMD5 di desain oleh Ronald Rivest pada tahun 1991 untuk menggantikan hash function sebelumnya, MD4.\nPada tahun 1996, sebuah kecacatan ditemukan dalam desainnya, walau bukan kelemahan fatal, pengguna kriptografi mulai menganjurkan menggunakan algoritme lain, seperti SHA-1 (klaim terbaru menyatakan bahwa SHA-1 juga cacat).\nPada tahun 2004, kecacatan-kecacatan yang lebih serius ditemukan menyebabkan penggunaan algoritme tersebut dalam tujuan untuk keamanan jadi makin dipertanyakan.....\n ");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Source:");

        TextWikipedia_.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        TextWikipedia_.setForeground(new java.awt.Color(51, 51, 255));
        TextWikipedia_.setText("wikipedia");
        TextWikipedia_.setToolTipText("Klik untuk membuka wikipedia");
        TextWikipedia_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextWikipedia_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextWikipedia_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextWikipedia_MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 3, 13)); // NOI18N
        jLabel4.setText("Apa itu SHA3-512 ?");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Banyak yang bertanya apa perbedaan SHA 2 dengan SHA 256? SHA 256 bit ini merupakan bagian dari SHA 2. Pengembangan projek SHA 2 yang dilakukan oleh pemerintah Amerika Serikat menghasilkan kurang lebih 4 SHA yang dikembangkan dan dimasukkan dalam kategori SHA 2 yakni SHA-224, SHA-384, SHA-512/224 dan SHA-512/256. SHA-512/256 ini merupakan SHA 2 dengan panjang hash 256 bit yang sering disebut dengan SHA 256.\n\nSaat ini penggunaan SHA 2 yang paling popular adalah SHA 256 bit yang menjadi standard untuk mendapatkan konfigurasi A+ SSL pada SSL Qlabs dengan tingkat keamanan sangat tinggi. Jadi SHA 2 dan SHA 256 adalah satu dan tidak ada beda. SHA 256 merupakan bagian dari SHA 2. SHA 2 ini akan berkaitan dengan algoritma hashing yang akan digunakan pada sertifikat root SSL.\n");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel5.setText("Source:");

        TextWikipedia2_.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        TextWikipedia2_.setForeground(new java.awt.Color(51, 51, 255));
        TextWikipedia2_.setText("wikipedia");
        TextWikipedia2_.setToolTipText("Klik untuk membuka wikipedia");
        TextWikipedia2_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextWikipedia2_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextWikipedia2_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextWikipedia2_MouseExited(evt);
            }
        });

        TextSSLIndonesia_.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        TextSSLIndonesia_.setForeground(new java.awt.Color(51, 51, 255));
        TextSSLIndonesia_.setText("SSL Indonesia");
        TextSSLIndonesia_.setToolTipText("Klik untuk membuka Link");
        TextSSLIndonesia_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextSSLIndonesia_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextSSLIndonesia_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextSSLIndonesia_MouseExited(evt);
            }
        });

        jLabel6.setText("&");

        TextSoniHendar_.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        TextSoniHendar_.setForeground(new java.awt.Color(0, 0, 255));
        TextSoniHendar_.setText("Soni Hendar // PTI 4B");
        TextSoniHendar_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextSoniHendar_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextSoniHendar_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextSoniHendar_MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextWikipedia_)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextWikipedia2_)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextSSLIndonesia_)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TextSoniHendar_)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextWikipedia_))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextWikipedia2_)
                    .addComponent(TextSSLIndonesia_)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(TextSoniHendar_))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextWikipedia_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextWikipedia_MouseClicked
        // TODO add your handling code here:
        TextWikipedia_.setForeground(Color.red);
        try {
            Desktop desktop = Desktop.getDesktop();
            URI url = new URI("https://id.wikipedia.org/wiki/MD5");
            if (Desktop.isDesktopSupported()) {
                try {
                    desktop.browse(url);
                } catch (IOException ex) {
                    System.out.println(ex);
                }
            }
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_TextWikipedia_MouseClicked

    private void TextWikipedia_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextWikipedia_MouseEntered
        // TODO add your handling code here:
        TextWikipedia_.setForeground(Color.red);
    }//GEN-LAST:event_TextWikipedia_MouseEntered

    private void TextWikipedia_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextWikipedia_MouseExited
        // TODO add your handling code here:
        TextWikipedia_.setForeground(Color.BLUE);
    }//GEN-LAST:event_TextWikipedia_MouseExited

    private void TextWikipedia2_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextWikipedia2_MouseClicked
        // TODO add your handling code here:
        TextWikipedia2_.setForeground(Color.red);
        try {
            Desktop desktop = Desktop.getDesktop();
            URI url = new URI("https://id.wikipedia.org/wiki/SHA-2");
            if (Desktop.isDesktopSupported()) {
                try {
                    desktop.browse(url);
                } catch (IOException ex) {
                    System.out.println(ex);
                }
            }
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_TextWikipedia2_MouseClicked

    private void TextWikipedia2_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextWikipedia2_MouseEntered
        // TODO add your handling code here:
        TextWikipedia2_.setForeground(Color.red);
    }//GEN-LAST:event_TextWikipedia2_MouseEntered

    private void TextWikipedia2_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextWikipedia2_MouseExited
        // TODO add your handling code here:
        TextWikipedia2_.setForeground(Color.BLUE);
    }//GEN-LAST:event_TextWikipedia2_MouseExited

    private void TextSSLIndonesia_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSSLIndonesia_MouseClicked
        // TODO add your handling code here:
        TextSSLIndonesia_.setForeground(Color.red);
        try {
            Desktop desktop = Desktop.getDesktop();
            URI url = new URI("https://sslindonesia.com/apa-perbedaan-enkripsi-pada-sha-1-sha-2-dan-sha-256-ssl-indonesia/");
            if (Desktop.isDesktopSupported()) {
                try {
                    desktop.browse(url);
                } catch (IOException ex) {
                    System.out.println(ex);
                }
            }
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_TextSSLIndonesia_MouseClicked

    private void TextSSLIndonesia_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSSLIndonesia_MouseEntered
        // TODO add your handling code here:
        TextSSLIndonesia_.setForeground(Color.red);
    }//GEN-LAST:event_TextSSLIndonesia_MouseEntered

    private void TextSSLIndonesia_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSSLIndonesia_MouseExited
        // TODO add your handling code here:
        TextSSLIndonesia_.setForeground(Color.BLUE);
    }//GEN-LAST:event_TextSSLIndonesia_MouseExited

    private void TextSoniHendar_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSoniHendar_MouseClicked
        // TODO add your handling code here:
        TextSoniHendar_.setForeground(Color.red);
        try {
            Desktop desktop = Desktop.getDesktop();
            URI url = new URI("https://github.com/Soni-Hendar-Kip");
            if (Desktop.isDesktopSupported()) {
                try {
                    desktop.browse(url);
                } catch (IOException ex) {
                    System.out.println(ex);
                }
            }
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_TextSoniHendar_MouseClicked

    private void TextSoniHendar_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSoniHendar_MouseEntered
        // TODO add your handling code here:
        TextSoniHendar_.setForeground(Color.red);
    }//GEN-LAST:event_TextSoniHendar_MouseEntered

    private void TextSoniHendar_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSoniHendar_MouseExited
        // TODO add your handling code here:
        TextSoniHendar_.setForeground(Color.BLUE);
    }//GEN-LAST:event_TextSoniHendar_MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Readme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Readme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Readme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Readme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Readme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextSSLIndonesia_;
    private javax.swing.JLabel TextSoniHendar_;
    private javax.swing.JLabel TextWikipedia2_;
    private javax.swing.JLabel TextWikipedia_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
